### ISSUE TITLE
"python setup.py egg_info" failed with error 

### ISSUE THREAD

**Issue by vkguda355** [crigroup/openrave-installation#10]
hi so when i try running the install openrave.sh , i get this error can you help me why i get this error?

https://pastebin.com/cu24w13U

thanks in advance

**Comment by nicholasadr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue. Thank you!
