### ISSUE TITLE
Cannot build in Ubuntu 16.04

### ISSUE THREAD

**Issue by thachdo** [crigroup/openrave-installation#15]
I try to follow the instructions to build the source files. It has been done without any error in Ubuntu 18.04. However, the following errors happen in Ubuntu 16.04 when I try to build the flexible collision library and the OpenRAVE. i.e., I cannot accomplish the following commands: 
```
./install-fcl.sh
./install-openrave.sh

```
Please take a look and give me some suggestions to overcome these issues.

**For the the flexible collision library the results are as follows.**

[  2%] Building CXX object src/CMakeFiles/fcl.dir/intersect.cpp.o
[  2%] Building CXX object src/CMakeFiles/fcl.dir/distance_func_matrix.cpp.o
[  3%] Building CXX object src/CMakeFiles/fcl.dir/collision_node.cpp.o
[  4%] Building CXX object src/CMakeFiles/fcl.dir/collision_func_matrix.cpp.o
[  5%] Building CXX object src/CMakeFiles/fcl.dir/shape/geometric_shapes.cpp.o
[  6%] Building CXX object src/CMakeFiles/fcl.dir/shape/geometric_shapes_utility.cpp.o
[  7%] Building CXX object src/CMakeFiles/fcl.dir/continuous_collision.cpp.o
[  8%] Building CXX object src/CMakeFiles/fcl.dir/ccd/motion.cpp.o
[ 10%] Building CXX object src/CMakeFiles/fcl.dir/ccd/interval_matrix.cpp.o
[ 11%] Building CXX object src/CMakeFiles/fcl.dir/ccd/interval_vector.cpp.o
[ 12%] Building CXX object src/CMakeFiles/fcl.dir/ccd/interpolation/interpolation_linear.cpp.o
[ 13%] Building CXX object src/CMakeFiles/fcl.dir/ccd/interpolation/interpolation_factory.cpp.o
[ 14%] Building CXX object src/CMakeFiles/fcl.dir/ccd/interpolation/interpolation.cpp.o
[ 15%] Building CXX object src/CMakeFiles/fcl.dir/ccd/taylor_matrix.cpp.o
[ 16%] Building CXX object src/CMakeFiles/fcl.dir/ccd/interval.cpp.o
[ 17%] Building CXX object src/CMakeFiles/fcl.dir/ccd/taylor_model.cpp.o
[ 18%] Building CXX object src/CMakeFiles/fcl.dir/ccd/taylor_vector.cpp.o
[ 20%] Building CXX object src/CMakeFiles/fcl.dir/ccd/conservative_advancement.cpp.o
[ 21%] Building CXX object src/CMakeFiles/fcl.dir/traversal/traversal_node_bvhs.cpp.o
[ 22%] Building CXX object src/CMakeFiles/fcl.dir/traversal/traversal_node_setup.cpp.o
[ 23%] Building CXX object src/CMakeFiles/fcl.dir/traversal/traversal_node_base.cpp.o
[ 24%] Building CXX object src/CMakeFiles/fcl.dir/traversal/traversal_recurse.cpp.o
[ 25%] Building CXX object src/CMakeFiles/fcl.dir/math/transform.cpp.o
[ 26%] Building CXX object src/CMakeFiles/fcl.dir/math/sampling.cpp.o
[ 27%] Building CXX object src/CMakeFiles/fcl.dir/collision_data.cpp.o
[ 28%] Building CXX object src/CMakeFiles/fcl.dir/collision.cpp.o
[ 30%] Building CXX object src/CMakeFiles/fcl.dir/BVH/BVH_utility.cpp.o
[ 31%] Building CXX object src/CMakeFiles/fcl.dir/BVH/BV_splitter.cpp.o
[ 32%] Building CXX object src/CMakeFiles/fcl.dir/BVH/BV_fitter.cpp.o
[ 33%] Building CXX object src/CMakeFiles/fcl.dir/BVH/BVH_model.cpp.o
[ 34%] Building CXX object src/CMakeFiles/fcl.dir/articulated_model/model.cpp.o
[ 35%] Building CXX object src/CMakeFiles/fcl.dir/articulated_model/link.cpp.o
[ 36%] Building CXX object src/CMakeFiles/fcl.dir/articulated_model/joint.cpp.o
[ 37%] Building CXX object src/CMakeFiles/fcl.dir/articulated_model/joint_config.cpp.o
[ 38%] Building CXX object src/CMakeFiles/fcl.dir/articulated_model/model_config.cpp.o
[ 40%] Building CXX object src/CMakeFiles/fcl.dir/BV/OBBRSS.cpp.o
[ 41%] Building CXX object src/CMakeFiles/fcl.dir/BV/OBB.cpp.o
[ 42%] Building CXX object src/CMakeFiles/fcl.dir/BV/RSS.cpp.o
[ 43%] Building CXX object src/CMakeFiles/fcl.dir/BV/kDOP.cpp.o
[ 44%] Building CXX object src/CMakeFiles/fcl.dir/BV/kIOS.cpp.o
[ 45%] Building CXX object src/CMakeFiles/fcl.dir/BV/AABB.cpp.o
[ 46%] Building CXX object src/CMakeFiles/fcl.dir/narrowphase/narrowphase.cpp.o
[ 47%] Building CXX object src/CMakeFiles/fcl.dir/narrowphase/gjk_libccd.cpp.o
[ 48%] Building CXX object src/CMakeFiles/fcl.dir/narrowphase/gjk.cpp.o
[ 50%] Building CXX object src/CMakeFiles/fcl.dir/profile.cpp.o
[ 51%] Building CXX object src/CMakeFiles/fcl.dir/distance.cpp.o
[ 52%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/interval_tree.cpp.o
[ 53%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/broadphase_spatialhash.cpp.o
[ 54%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/broadphase_interval_tree.cpp.o
[ 55%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/hierarchy_tree.cpp.o
[ 56%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/broadphase_SSaP.cpp.o
[ 57%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/broadphase_dynamic_AABB_tree.cpp.o
[ 58%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/broadphase_bruteforce.cpp.o
[ 60%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/broadphase_SaP.cpp.o
[ 61%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/broadphase_dynamic_AABB_tree_array.cpp.o
In file included from /home/thachdo/git/fcl/include/fcl/broadphase/hierarchy_tree.h:589:0,
                 from /home/thachdo/git/fcl/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h:43,
                 from /home/thachdo/git/fcl/include/fcl/broadphase/broadphase.h:238,
                 from /home/thachdo/git/fcl/include/fcl/broadphase/broadphase_dynamic_AABB_tree_array.h:41,
                 from /home/thachdo/git/fcl/src/broadphase/broadphase_dynamic_AABB_tree_array.cpp:38:
/home/thachdo/git/fcl/include/fcl/broadphase/hierarchy_tree.hxx: In member function ‘void fcl::implementation_array::HierarchyTree<BV>::init_3(fcl::implementation_array::HierarchyTree<BV>::NodeType*, int) [with BV = fcl::AABB; fcl::implementation_array::HierarchyTree<BV>::NodeType = fcl::implementation_array::NodeBase<fcl::AABB>]’:
/home/thachdo/git/fcl/include/fcl/broadphase/hierarchy_tree.hxx:1121:16: warning: ‘*((void*)& comp +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   SortByMorton comp;
                ^
/home/thachdo/git/fcl/include/fcl/broadphase/hierarchy_tree.hxx: In member function ‘void fcl::implementation_array::HierarchyTree<BV>::init_2(fcl::implementation_array::HierarchyTree<BV>::NodeType*, int) [with BV = fcl::AABB; fcl::implementation_array::HierarchyTree<BV>::NodeType = fcl::implementation_array::NodeBase<fcl::AABB>]’:
/home/thachdo/git/fcl/include/fcl/broadphase/hierarchy_tree.hxx:1077:16: warning: ‘*((void*)& comp +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   SortByMorton comp;
                ^
/home/thachdo/git/fcl/include/fcl/broadphase/hierarchy_tree.hxx: In member function ‘void fcl::implementation_array::HierarchyTree<BV>::init_1(fcl::implementation_array::HierarchyTree<BV>::NodeType*, int) [with BV = fcl::AABB; fcl::implementation_array::HierarchyTree<BV>::NodeType = fcl::implementation_array::NodeBase<fcl::AABB>]’:
/home/thachdo/git/fcl/include/fcl/broadphase/hierarchy_tree.hxx:1033:16: warning: ‘*((void*)& comp +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   SortByMorton comp;
                ^
[ 62%] Linking CXX shared library ../lib/libfcl.so
[ 62%] Built target fcl
[ 63%] Building CXX object test/CMakeFiles/test_fcl_bvh_models.dir/test_fcl_bvh_models.cpp.o
[ 64%] Building CXX object test/CMakeFiles/test_fcl_simple.dir/test_fcl_simple.cpp.o
[ 65%] Building CXX object test/CMakeFiles/test_fcl_broadphase.dir/test_fcl_broadphase.cpp.o
[ 66%] Building CXX object test/CMakeFiles/test_fcl_capsule_box_1.dir/test_fcl_capsule_box_1.cpp.o
[ 67%] Building CXX object test/CMakeFiles/test_fcl_shape_mesh_consistency.dir/test_fcl_shape_mesh_consistency.cpp.o
[ 68%] Building CXX object test/CMakeFiles/test_fcl_collision.dir/test_fcl_collision.cpp.o
[ 70%] Building CXX object test/CMakeFiles/test_fcl_capsule_box_2.dir/test_fcl_capsule_box_2.cpp.o
[ 71%] Building CXX object test/CMakeFiles/test_fcl_distance.dir/test_fcl_distance.cpp.o
[ 72%] Linking CXX executable test_fcl_capsule_box_1
CMakeFiles/test_fcl_capsule_box_1.dir/test_fcl_capsule_box_1.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_fcl_capsule_box_1.dir/build.make:99: recipe for target 'test/test_fcl_capsule_box_1' failed
make[2]: *** [test/test_fcl_capsule_box_1] Error 1
CMakeFiles/Makefile2:325: recipe for target 'test/CMakeFiles/test_fcl_capsule_box_1.dir/all' failed
make[1]: *** [test/CMakeFiles/test_fcl_capsule_box_1.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 73%] Building CXX object test/CMakeFiles/test_fcl_collision.dir/test_fcl_utility.cpp.o
[ 74%] Linking CXX executable test_fcl_capsule_box_2
CMakeFiles/test_fcl_capsule_box_2.dir/test_fcl_capsule_box_2.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_fcl_capsule_box_2.dir/build.make:99: recipe for target 'test/test_fcl_capsule_box_2' failed
make[2]: *** [test/test_fcl_capsule_box_2] Error 1
CMakeFiles/Makefile2:473: recipe for target 'test/CMakeFiles/test_fcl_capsule_box_2.dir/all' failed
make[1]: *** [test/CMakeFiles/test_fcl_capsule_box_2.dir/all] Error 2
[ 75%] Building CXX object test/CMakeFiles/test_fcl_bvh_models.dir/test_fcl_utility.cpp.o
[ 76%] Building CXX object test/CMakeFiles/test_fcl_shape_mesh_consistency.dir/test_fcl_utility.cpp.o
[ 77%] Building CXX object test/CMakeFiles/test_fcl_distance.dir/test_fcl_utility.cpp.o
[ 78%] Linking CXX executable test_fcl_simple
CMakeFiles/test_fcl_simple.dir/test_fcl_simple.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_fcl_simple.dir/build.make:99: recipe for target 'test/test_fcl_simple' failed
make[2]: *** [test/test_fcl_simple] Error 1
CMakeFiles/Makefile2:362: recipe for target 'test/CMakeFiles/test_fcl_simple.dir/all' failed
make[1]: *** [test/CMakeFiles/test_fcl_simple.dir/all] Error 2
[ 80%] Building CXX object test/CMakeFiles/test_fcl_broadphase.dir/test_fcl_utility.cpp.o
[ 81%] Linking CXX executable test_fcl_bvh_models
CMakeFiles/test_fcl_bvh_models.dir/test_fcl_bvh_models.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
[ 82%] Linking CXX executable test_fcl_distance
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_fcl_bvh_models.dir/build.make:125: recipe for target 'test/test_fcl_bvh_models' failed
make[2]: *** [test/test_fcl_bvh_models] Error 1
CMakeFiles/Makefile2:214: recipe for target 'test/CMakeFiles/test_fcl_bvh_models.dir/all' failed
make[1]: *** [test/CMakeFiles/test_fcl_bvh_models.dir/all] Error 2
CMakeFiles/test_fcl_distance.dir/test_fcl_distance.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
[ 83%] Linking CXX executable test_fcl_broadphase
CMakeFiles/test_fcl_broadphase.dir/test_fcl_broadphase.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_fcl_distance.dir/build.make:125: recipe for target 'test/test_fcl_distance' failed
make[2]: *** [test/test_fcl_distance] Error 1
CMakeFiles/Makefile2:436: recipe for target 'test/CMakeFiles/test_fcl_distance.dir/all' failed
make[1]: *** [test/CMakeFiles/test_fcl_distance.dir/all] Error 2
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_fcl_broadphase.dir/build.make:125: recipe for target 'test/test_fcl_broadphase' failed
make[2]: *** [test/test_fcl_broadphase] Error 1
CMakeFiles/Makefile2:251: recipe for target 'test/CMakeFiles/test_fcl_broadphase.dir/all' failed
make[1]: *** [test/CMakeFiles/test_fcl_broadphase.dir/all] Error 2
[ 84%] Linking CXX executable test_fcl_collision
CMakeFiles/test_fcl_collision.dir/test_fcl_collision.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_fcl_collision.dir/build.make:125: recipe for target 'test/test_fcl_collision' failed
make[2]: *** [test/test_fcl_collision] Error 1
CMakeFiles/Makefile2:399: recipe for target 'test/CMakeFiles/test_fcl_collision.dir/all' failed
make[1]: *** [test/CMakeFiles/test_fcl_collision.dir/all] Error 2
[ 85%] Linking CXX executable test_fcl_shape_mesh_consistency
CMakeFiles/test_fcl_shape_mesh_consistency.dir/test_fcl_shape_mesh_consistency.cpp.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
test/CMakeFiles/test_fcl_shape_mesh_consistency.dir/build.make:125: recipe for target 'test/test_fcl_shape_mesh_consistency' failed
make[2]: *** [test/test_fcl_shape_mesh_consistency] Error 1
CMakeFiles/Makefile2:288: recipe for target 'test/CMakeFiles/test_fcl_shape_mesh_consistency.dir/all' failed
make[1]: *** [test/CMakeFiles/test_fcl_shape_mesh_consistency.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**For the OpenRAVE, results are as follows.**

[ 80%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/qtreemodel.cpp.o
[ 81%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/osgrenderitem.cpp.o
[ 81%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/qtreeitem.cpp.o
[ 81%] Linking CXX shared library librmanipulation.so
[ 81%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/qtosgviewer.cpp.o
[ 81%] Building CXX object plugins/qtcoinrave/CMakeFiles/qtcoinrave.dir/qtcoinviewer.cpp.o
[ 81%] Built target rmanipulation
[ 82%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/qtosgrave.cpp.o
Scanning dependencies of target libopenrave-core_c
[ 83%] Linking CXX executable openrave0.9
[ 83%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/osgskybox.cpp.o
[ 84%] Building CXX object src/libopenrave-core/CMakeFiles/libopenrave-core_c.dir/openrave-core_c.cpp.o
CMakeFiles/openrave.dir/openrave.cpp.o: In function `OpenRAVE::RavePrintfA_WARNLEVEL(log4cxx::helpers::ObjectPtrT<log4cxx::Logger> const&, log4cxx::spi::LocationInfo const&, char const*, ...)':
openrave.cpp:(.text._ZN8OpenRAVE21RavePrintfA_WARNLEVELERKN7log4cxx7helpers10ObjectPtrTINS0_6LoggerEEERKNS0_3spi12LocationInfoEPKcz[_ZN8OpenRAVE21RavePrintfA_WARNLEVELERKN7log4cxx7helpers10ObjectPtrTINS0_6LoggerEEERKNS0_3spi12LocationInfoEPKcz]+0x28e): undefined reference to `log4cxx::Logger::forcedLog(log4cxx::helpers::ObjectPtrT<log4cxx::Level> const&, std::string const&, log4cxx::spi::LocationInfo const&) const'
CMakeFiles/openrave.dir/openrave.cpp.o: In function `OpenRAVE::RavePrintfA_DEBUGLEVEL(log4cxx::helpers::ObjectPtrT<log4cxx::Logger> const&, log4cxx::spi::LocationInfo const&, char const*, ...)':
openrave.cpp:(.text._ZN8OpenRAVE22RavePrintfA_DEBUGLEVELERKN7log4cxx7helpers10ObjectPtrTINS0_6LoggerEEERKNS0_3spi12LocationInfoEPKcz[_ZN8OpenRAVE22RavePrintfA_DEBUGLEVELERKN7log4cxx7helpers10ObjectPtrTINS0_6LoggerEEERKNS0_3spi12LocationInfoEPKcz]+0x28e): undefined reference to `log4cxx::Logger::forcedLog(log4cxx::helpers::ObjectPtrT<log4cxx::Level> const&, std::string const&, log4cxx::spi::LocationInfo const&) const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeElement::getCharData()'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::PatternLayout::PatternLayout(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::id() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::nativePathToUri(std::string const&, cdom::systemType)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::parseUriRef(std::string const&, std::string&, std::string&, std::string&, std::string&, std::string&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::str() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::set(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, daeURI const*)'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::Layout::appendFooter(std::string&, log4cxx::helpers::Pool&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::daeURI(daeElement&, std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::operator=(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::getCurrentDirAsUri()'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::daeURI(DAE&, std::string const&, bool)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::query(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeSidRef::daeSidRef(std::string const&, daeElement*, std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeElement::setCharData(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeDatabase::idLookup(std::string const&, daeDocument*)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::assembleUri(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, bool)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeElement::getAttribute(char const*)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::fragment(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::id(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::daeURI(daeURI const&, std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::path() const'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::Layout::appendHeader(std::string&, log4cxx::helpers::Pool&)'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::Level::Level(int, std::string const&, int)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::scheme() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::authority() const'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::Layout::getContentType() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::uriToFilePath(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::fragment() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::query() const'
[ 84%] Linking CXX shared library liboderave.so
collect2: error: ld returned 1 exit status
src/CMakeFiles/openrave.dir/build.make:111: recipe for target 'src/openrave0.9' failed
make[2]: *** [src/openrave0.9] Error 1
CMakeFiles/Makefile2:650: recipe for target 'src/CMakeFiles/openrave.dir/all' failed
make[1]: *** [src/CMakeFiles/openrave.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/moc_qtosgviewer.cxx.o
[ 84%] Built target oderave
[ 85%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/moc_qtreemodel.cxx.o
[ 85%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/qrc_qtosgviewer.cxx.o
[ 86%] Building CXX object plugins/qtcoinrave/CMakeFiles/qtcoinrave.dir/qtcoinrave.cpp.o
[ 86%] Building CXX object plugins/qtcoinrave/CMakeFiles/qtcoinrave.dir/moc_qtcoinviewer.cxx.o
[ 86%] Linking CXX shared library libopenrave0.9-core_c.so
[ 86%] Built target libopenrave-core_c
[ 86%] Building CXX object plugins/qtcoinrave/CMakeFiles/qtcoinrave.dir/ivmodelloader.cpp.o
[ 87%] Linking CXX shared library libqtcoinrave.so
[ 87%] Linking CXX shared library libqtosgrave.so
[ 87%] Built target qtosgrave
[ 87%] Built target qtcoinrave
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[  1%] Built target openrave-md5-native
[  3%] Built target cpp-gen-md5-native
[  3%] Built target interfacehashes_target
[  3%] Built target openrave-md5
[ 13%] Built target crlibm
[ 22%] Built target crlibm-native
[ 23%] Built target ivcon
[ 27%] Built target ANN
[ 28%] Built target fparser
[ 31%] Built target convexdecomposition
[ 32%] Built target check_libm_accuracy-native
[ 39%] Built target libopenrave
[ 43%] Built target libopenrave-core
[ 44%] Linking CXX executable openrave0.9
CMakeFiles/openrave.dir/openrave.cpp.o: In function `OpenRAVE::RavePrintfA_WARNLEVEL(log4cxx::helpers::ObjectPtrT<log4cxx::Logger> const&, log4cxx::spi::LocationInfo const&, char const*, ...)':
openrave.cpp:(.text._ZN8OpenRAVE21RavePrintfA_WARNLEVELERKN7log4cxx7helpers10ObjectPtrTINS0_6LoggerEEERKNS0_3spi12LocationInfoEPKcz[_ZN8OpenRAVE21RavePrintfA_WARNLEVELERKN7log4cxx7helpers10ObjectPtrTINS0_6LoggerEEERKNS0_3spi12LocationInfoEPKcz]+0x28e): undefined reference to `log4cxx::Logger::forcedLog(log4cxx::helpers::ObjectPtrT<log4cxx::Level> const&, std::string const&, log4cxx::spi::LocationInfo const&) const'
CMakeFiles/openrave.dir/openrave.cpp.o: In function `OpenRAVE::RavePrintfA_DEBUGLEVEL(log4cxx::helpers::ObjectPtrT<log4cxx::Logger> const&, log4cxx::spi::LocationInfo const&, char const*, ...)':
openrave.cpp:(.text._ZN8OpenRAVE22RavePrintfA_DEBUGLEVELERKN7log4cxx7helpers10ObjectPtrTINS0_6LoggerEEERKNS0_3spi12LocationInfoEPKcz[_ZN8OpenRAVE22RavePrintfA_DEBUGLEVELERKN7log4cxx7helpers10ObjectPtrTINS0_6LoggerEEERKNS0_3spi12LocationInfoEPKcz]+0x28e): undefined reference to `log4cxx::Logger::forcedLog(log4cxx::helpers::ObjectPtrT<log4cxx::Level> const&, std::string const&, log4cxx::spi::LocationInfo const&) const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeElement::getCharData()'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::PatternLayout::PatternLayout(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::id() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::nativePathToUri(std::string const&, cdom::systemType)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::parseUriRef(std::string const&, std::string&, std::string&, std::string&, std::string&, std::string&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::str() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::set(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, daeURI const*)'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::Layout::appendFooter(std::string&, log4cxx::helpers::Pool&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::daeURI(daeElement&, std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::operator=(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::getCurrentDirAsUri()'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::daeURI(DAE&, std::string const&, bool)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::query(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeSidRef::daeSidRef(std::string const&, daeElement*, std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeElement::setCharData(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeDatabase::idLookup(std::string const&, daeDocument*)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::assembleUri(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, bool)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeElement::getAttribute(char const*)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::fragment(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::id(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::daeURI(daeURI const&, std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::path() const'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::Layout::appendHeader(std::string&, log4cxx::helpers::Pool&)'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::Level::Level(int, std::string const&, int)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::scheme() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::authority() const'
libopenrave/libopenrave0.9.so.0.9.0: undefined reference to `log4cxx::Layout::getContentType() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `cdom::uriToFilePath(std::string const&)'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::fragment() const'
libopenrave-core/libopenrave0.9-core.so.0.9.0: undefined reference to `daeURI::query() const'
collect2: error: ld returned 1 exit status
src/CMakeFiles/openrave.dir/build.make:111: recipe for target 'src/openrave0.9' failed
make[2]: *** [src/openrave0.9] Error 1
CMakeFiles/Makefile2:650: recipe for target 'src/CMakeFiles/openrave.dir/all' failed
make[1]: *** [src/CMakeFiles/openrave.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nicholasadr** [comment]
Hi @thachdo, it seems that the problem is related to an issue with dependencies installation. Have you successfully run `./install-dependencies.sh`?

**Comment by robopassio** [comment]
Thank @nicholasadr. Yes, I successfully did it. However, to overcome those errors, I have been choosing to run on Ubuntu 18.04 instead.

**Comment by thachdo** [comment]
Thank @nicholasadr. Yes, I successfully did it. However, to overcome those errors, I have been choosing to run on Ubuntu 18.04 instead.
