### ISSUE TITLE
Missing build packages cause 'failed to find an OpenRAVE viewer' error

### ISSUE THREAD

**Issue by zenakuten** [crigroup/openrave-installation#17]
After installation, when running openrave on Ubuntu 18.04 (wsl) I receive this error:

    openrave [WARN] [openrave.cpp:322 MainOpenRAVEThread] failed to find an OpenRAVE viewer.

To fix it, I had to install these packages:

    sudo apt-get install libqt4-dev libsoqt-dev-common libsoqt4-dev

and then re-run ./install-openrave.sh

**Comment by nicholasadr** [comment]
Hi @zenakuten, thanks for raising the issue. The problem should be fixed with the recent commit. Let me know if the problem still persists and I can reopen.
