### ISSUE TITLE
Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by mrahtz** [crigroup/openrave-installation#4]
Thanks for this repo! The README suggests support for Ubuntu 18.04, but I see that commit b9fdc9a seems to revert a number of 18.04-specific changes. I've dabbled with compiling on 18.04 by adding back some of these changes, but got compiler errors. Were you ever able to get it running on 18.04, or is there some reason that it's not possible?

**Comment by fsuarez6** [comment]
Yes, it supports 18.04. We have succeeded to install it on couple of machines. 
Did you try the latest commit?

**Comment by naldorinho** [comment]
Thanks for the repo! I have tried the latest commit for 18.04 and i'm still having problems with some errors installing the last install-openrave.sh file.

python/bindings/CMakeFiles/pyANN_int.dir/build.make:62: recipe for target 'python/bindings/CMakeFiles/pyANN_int.dir/pyann.cpp.o' failed
make[2]: *** [python/bindings/CMakeFiles/pyANN_int.dir/pyann.cpp.o] Error 1
CMakeFiles/Makefile2:1158: recipe for target 'python/bindings/CMakeFiles/pyANN_int.dir/all' failed
make[1]: *** [python/bindings/CMakeFiles/pyANN_int.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Do you know any solution? Thanks!

**Comment by fsuarez8** [comment]
Can you share the full output?
Please share it using something like https://pastebin.com/

**Comment by naldorinho** [comment]
The whole output of the comand window when installing openrave in ubuntu 18.04 https://pastebin.com/NX0bpQuZ

**Comment by fsuarez6** [comment]
OK. I need some time to test on a fresh Ubuntu 18.04 container.

**Comment by fsuarez6** [comment]
The issue you encounter is due to a deprecation in Boost. 
According to the [Boost 1.65 release notes](http://www.boost.org/users/history/version_1_65_1.html):

> The boost::python::numeric API has been removed, as it is being obsoleted by boost::python::numpy.

Please try the latest commit. I've changed the scripts to install boost 1.58 from source for Ubuntu 18.04.

**Comment by naldorinho** [comment]
It works! Thank you for the help!!
